-- 017_agent_tools_support.sql

-- Add new columns for agent tools support
ALTER TABLE skills ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS source_branch TEXT DEFAULT 'main';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS source_path TEXT;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS install_command TEXT;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS license TEXT DEFAULT 'MIT';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS stars_count INTEGER DEFAULT 0;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS forks_count INTEGER DEFAULT 0;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS archive_url TEXT;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS file_manifest JSONB DEFAULT '[]';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS readme_content TEXT;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS metadata_json JSONB DEFAULT '{}';
ALTER TABLE skills ADD COLUMN IF NOT EXISTS total_files INTEGER DEFAULT 1;
ALTER TABLE skills ADD COLUMN IF NOT EXISTS related_occupations JSONB DEFAULT '[]';
